Deck.create(name: "Ruby Enumerables")

Card.create(question: "Passes each element of the collection to the given block. The method returns true if the block ever returns a value other than false or nil. If the block is not given, Ruby adds an implicit block of { |obj| obj } that will cause _____ to return true if at least one of the collection members is not false or nil.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)", answer: '.any?', deck_id: 8)
Card.create(question: "Passes each element of the collection to the given block. The method returns true if the block never returns false or nil. If the block is not given, Ruby adds an implicit block of { |obj| obj } which will cause ______ to return true when none of the collection members are false or nil.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
) ", answer: '.all?', deck_id: 8)
Card.create(question: "Passes each entry in enum to block. Returns the first for which block is not false. If no object matches, calls ifnone and returns its result when it is specified, or returns nil otherwise.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)" , answer: ".find", deck_id: 8)
Card.create(question: "Combines all elements of enum by applying a binary operation, specified by a block or a symbol that names a method or operator.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)", answer: ".reduce", deck_id: 8)
Card.create(question: "Returns true if any member of enum equals obj. Equality is tested using ==.         (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)", answer: ".include?", deck_id: 8)
Card.create(question: "Returns an array containing the items in enum _____ed.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)", answer: ".sort", deck_id: 8)
Card.create(question: "Returns an array containing all elements of enum for which the given block returns a true value.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)", answer: ".select", deck_id: 8)
Card.create(question: "Sorts enum using a set of keys generated by mapping the values in enum through the given block.        (POSSIBILITIES: .select / .find  / .all? / .sort / . any? / .include? / .reduce / .sort_by /
)", answer: ".sort_by", deck_id: 8)
